"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useState, useEffect, useRef } from "react";
import { useSearchParams } from "next/navigation";
import { 
  Cpu, Code2, Terminal, Activity, FileJson, 
  Play, Save, Bug, CheckCircle2, ChevronRight,
  Layers, Database, Shield, Globe
} from "lucide-react";
import Editor from "@monaco-editor/react";
import { Sidebar } from "@/components/layout/sidebar";
import toast from "react-hot-toast";

// --- Mock Data & Constants ---
const AGENT_SEQUENCE = ["architect", "backend", "frontend", "qa", "devops", "security"];

export default function EngineeringWorkspace() {
  const searchParams = useSearchParams();
  const initialRequirement = searchParams.get("req") || "";
  
  const [activeTab, setActiveTab] = useState<"code" | "plan" | "debug">("code");
  const [activeFile, setActiveFile] = useState("main.py");
  const [currentAgentIndex, setCurrentAgentIndex] = useState(0);
  const [logs, setLogs] = useState<Array<{ agent: string; message: string; type: 'info' | 'success' | 'error' | 'warning' }>>([]);
  const [generatedCode, setGeneratedCode] = useState<Record<string, string>>({
    "main.py": "# Initializing project...\n\nimport os\n\n# Your production code will appear here.",
    "models.py": "from sqlalchemy import Column, Integer, String\n\n# Data models being designed...",
    "README.md": "# Project Documentation\n\nGenerated by NEXUS OS."
  });
  
  const logEndRef = useRef<HTMLDivElement>(null);

  // --- Cinematic Logic ---
  useEffect(() => {
    if (!initialRequirement) return;

    const startPipeline = async () => {
      addLog("system", "Initializing Autonomous Engineering Pipeline...", "info");
      await wait(1000);
      
      // Architect Phase
      addLog("architect", "Analyzing requirements semantically...", "info");
      await wait(2000);
      addLog("architect", "Inferring optimal system architecture...", "info");
      await wait(1500);
      addLog("architect", "Design pattern: Microservices with Event-Driven Architecture", "success");
      setCurrentAgentIndex(1);

      // Backend Phase
      addLog("backend", "Generating FastAPI service layer...", "info");
      await wait(2000);
      setGeneratedCode(prev => ({
        ...prev,
        "api/main.py": "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/')\nasync def root():\n    return {'status': 'operational'}"
      }));
      setActiveFile("api/main.py");
      addLog("backend", "Schema inference complete. Generated 5 models.", "success");
      setCurrentAgentIndex(2);

      // Continue the cinematic flow...
    };

    startPipeline();
  }, [initialRequirement]);

  useEffect(() => {
    logEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs]);

  const addLog = (agent: string, message: string, type: any) => {
    setLogs(prev => [...prev, { agent, message, type }]);
  };

  const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

  return (
    <div className="flex min-h-screen bg-nexus-void text-nexus-text">
      <Sidebar />
      
      <main className="ml-[72px] flex-1 flex flex-col h-screen overflow-hidden">
        {/* Top Header Bar */}
        <header className="h-14 border-b border-nexus-border flex items-center justify-between px-6 glass">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold uppercase tracking-widest text-nexus-muted">Task ID:</span>
              <span className="text-xs font-mono text-nexus-primary">ENG-{Math.random().toString(36).substring(7).toUpperCase()}</span>
            </div>
            <div className="h-4 w-[1px] bg-nexus-border" />
            <div className="flex items-center gap-2">
              <Activity size={14} className="text-nexus-emerald animate-pulse" />
              <span className="text-xs font-medium text-nexus-emerald">Pipeline Active</span>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-nexus-elevated border border-nexus-border hover:border-nexus-border-bright transition-all text-xs">
              <Save size={14} />
              Save State
            </button>
            <button className="btn-primary flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs">
              <Play size={14} />
              Execute Tests
            </button>
          </div>
        </header>

        {/* Workspace Layout */}
        <div className="flex-1 flex overflow-hidden">
          {/* File Explorer & Agent Status */}
          <aside className="w-64 border-right border-nexus-border flex flex-col glass">
            <div className="p-4 border-b border-nexus-border">
              <h3 className="text-[10px] font-bold uppercase tracking-widest text-nexus-muted mb-4">Pipeline Progress</h3>
              <div className="flex flex-col gap-3">
                {AGENT_SEQUENCE.map((agent, i) => (
                  <div key={agent} className="flex items-center gap-3">
                    <div className={`w-1.5 h-1.5 rounded-full ${i <= currentAgentIndex ? 'bg-nexus-primary shadow-[0_0_8px_#6366f1]' : 'bg-nexus-elevated'}`} />
                    <span className={`text-xs capitalize ${i === currentAgentIndex ? 'text-nexus-text font-bold' : 'text-nexus-muted'}`}>
                      {agent}
                    </span>
                    {i < currentAgentIndex && <CheckCircle2 size={12} className="text-nexus-emerald ml-auto" />}
                    {i === currentAgentIndex && <div className="w-1.5 h-1.5 bg-nexus-primary rounded-full animate-ping ml-auto" />}
                  </div>
                ))}
              </div>
            </div>

            <div className="p-4 flex-1 overflow-y-auto">
              <h3 className="text-[10px] font-bold uppercase tracking-widest text-nexus-muted mb-4">Generated Files</h3>
              <div className="flex flex-col gap-1">
                {Object.keys(generatedCode).map(file => (
                  <button 
                    key={file}
                    onClick={() => setActiveFile(file)}
                    className={`flex items-center gap-2 px-2 py-1.5 rounded-lg text-xs transition-colors ${activeFile === file ? 'bg-nexus-primary/20 text-nexus-primary border border-nexus-primary/30' : 'text-nexus-muted hover:bg-white/5'}`}
                  >
                    <Code2 size={14} />
                    {file}
                  </button>
                ))}
              </div>
            </div>
          </aside>

          {/* Main Editor Area */}
          <div className="flex-1 flex flex-col min-w-0 bg-[#050508]">
            <div className="h-10 flex items-center px-4 gap-4 border-b border-nexus-border bg-nexus-deep">
              <button 
                onClick={() => setActiveTab('code')}
                className={`text-[11px] font-bold uppercase tracking-wider transition-colors ${activeTab === 'code' ? 'text-nexus-primary' : 'text-nexus-muted'}`}
              >
                Source Code
              </button>
              <button 
                onClick={() => setActiveTab('plan')}
                className={`text-[11px] font-bold uppercase tracking-wider transition-colors ${activeTab === 'plan' ? 'text-nexus-primary' : 'text-nexus-muted'}`}
              >
                Engineering Plan
              </button>
              <button 
                onClick={() => setActiveTab('debug')}
                className={`text-[11px] font-bold uppercase tracking-wider transition-colors ${activeTab === 'debug' ? 'text-nexus-primary' : 'text-nexus-muted'}`}
              >
                Debug Analysis
              </button>
            </div>
            
            <div className="flex-1 relative">
              <Editor
                height="100%"
                theme="vs-dark"
                path={activeFile}
                defaultLanguage="python"
                value={generatedCode[activeFile]}
                options={{
                  fontSize: 13,
                  fontFamily: "'JetBrains Mono', monospace",
                  minimap: { enabled: false },
                  scrollBeyondLastLine: false,
                  lineNumbers: "on",
                  glyphMargin: true,
                  folding: true,
                  lineDecorationsWidth: 10,
                  contextmenu: true,
                  renderLineHighlight: "all",
                  backgroundColor: "#050508"
                }}
              />
            </div>
          </div>

          {/* Activity Log & Terminal */}
          <aside className="w-80 border-l border-nexus-border flex flex-col glass">
            <div className="flex-1 flex flex-col overflow-hidden">
              <div className="p-4 border-b border-nexus-border flex items-center justify-between">
                <h3 className="text-[10px] font-bold uppercase tracking-widest text-nexus-muted">Agent Activity Log</h3>
                <Terminal size={14} className="text-nexus-muted" />
              </div>
              
              <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-3 font-mono text-[11px]">
                {logs.map((log, i) => (
                  <motion.div 
                    key={i}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    className={`flex flex-col gap-1 border-l-2 pl-3 ${
                      log.type === 'success' ? 'border-nexus-emerald' : 
                      log.type === 'error' ? 'border-nexus-rose' : 
                      log.type === 'warning' ? 'border-nexus-amber' : 'border-nexus-primary'
                    }`}
                  >
                    <span className="text-[9px] uppercase font-bold text-nexus-muted">[{log.agent}]</span>
                    <p className={
                      log.type === 'success' ? 'text-nexus-emerald' : 
                      log.type === 'error' ? 'text-nexus-rose' : 
                      log.type === 'warning' ? 'text-nexus-amber' : 'text-gray-300'
                    }>
                      {log.message}
                    </p>
                  </motion.div>
                ))}
                <div ref={logEndRef} />
              </div>
            </div>

            <div className="h-48 border-t border-nexus-border bg-black flex flex-col">
              <div className="px-4 py-2 border-b border-nexus-border flex items-center gap-2">
                <Terminal size={12} className="text-nexus-emerald" />
                <span className="text-[10px] font-bold uppercase tracking-widest text-nexus-muted">Autonomous Terminal</span>
              </div>
              <div className="flex-1 p-4 font-mono text-[11px] text-nexus-emerald overflow-y-auto">
                <p>$ nexus execute --sandbox py312</p>
                <p className="text-gray-500 mt-1">Starting ephemeral execution environment...</p>
                <p className="text-gray-500">Mounting /workspace [RO]</p>
                <p className="mt-2 text-white font-bold">Successfully initialized sandbox.</p>
                <p className="animate-pulse">_</p>
              </div>
            </div>
          </aside>
        </div>
      </main>
    </div>
  );
}
